---
title: "final proj exploration"
author: "Yuelin He"
date: "11/14/2021"
output: pdf_document
---

# Read-in data
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(srvyr)
library(corrplot)
library(ggplot2)
library(srvyr)

adult20 <- read.csv('adult20.csv')
```


## Variable selections & data cleaning

```{r}
data_new <- adult20 %>% select(
  ##survey design
  HHX, WTFA_A, URBRRL, REGION, PSTRAT, PPSU,
  ## outcome
  MHRX_A, MHTHRPY_A, # mental health
  DEPEV_A, DEPFREQ_A, DEPMED_A, # depression
  ANXEV_A, ANXFREQ_A, ANXMED_A, # anxiety
  ##predictors
  CVDDIAG_A, COVIDTEST_A, # covid test
  DLYCARE_A, DNGCARE_A, VIRAPP12M_A, # access to care due to covid
  HOMECAREDG_A, FAMCARE12M_A, FAMCAREDNG_A, # family care due to covid
  ##confounders ## no NAs
  AGEP_A, SEX_A, EDUC_A, 
  HISPALLP_A # r/e
  ) 

# remove NAs in the COVID related questions of our interest
data_new <- data_new %>% drop_na(CVDDIAG_A, COVIDTEST_A, DLYCARE_A, DNGCARE_A, VIRAPP12M_A,HOMECAREDG_A, FAMCARE12M_A, FAMCAREDNG_A)
# 17712 rows, 30 columns

# corrplot(as.matrix(data_new[,2:16]))


# recode yes/no data
binary_var <- c("MHRX_A", "MHTHRPY_A", "DEPEV_A", "DEPMED_A", "ANXEV_A", "ANXMED_A", "CVDDIAG_A", "COVIDTEST_A", "DLYCARE_A", "DNGCARE_A", "VIRAPP12M_A", "HOMECAREDG_A", "FAMCARE12M_A", "FAMCAREDNG_A")
for (i in binary_var){
  data_new[,i] <- dplyr::recode(as.character(data_new[,i]),
                                '1'='Yes','2'='No','7'='Refused',
                                '8'='Not ascertained','9'='unknown')
}

# recode frequency data
for (i in c('DEPFREQ_A','ANXFREQ_A')){
  data_new[,i] <- dplyr::recode(as.character(data_new[,i]),
                                '1'='Daily','2'='Weekly','3'='Monthly',
                                '4'='A few times a year','5'='Never',
                                '7'='Refused', '8'='Not ascertained','9'='unknown')
}

# recode others
data_new[,'SEX_A'] <- dplyr::recode(as.character(data_new[,'SEX_A']),
                                '1'='Male','2'='Female','7'='Refused',
                                '8'='Not ascertained','9'='unknown')
data_new$EDUC_A <- ifelse(data_new$EDUC_A<=11&data_new$EDUC_A>=5,5,data_new$EDUC_A)
data_new$EDUC_A <- ifelse(data_new$EDUC_A<=4,0,data_new$EDUC_A)
data_new$EDUC_A <- ifelse(data_new$EDUC_A%in% c(0,5),data_new$EDUC_A,NA)
data_new$EDUC_A <- dplyr::recode(as.character(data_new$EDUC_A),
                                '0'='High School or Below','5'='College or Above')
data_new$HISPALLP_A <- dplyr::recode(as.character(data_new$HISPALLP_A),
                                '1'='Hispanic','2'='NH White',
                                '3'='Black/African American','4'='Asian',
                                '5'='AIAN','6'='AIAN and any other group',
                                '7'='Other single and multiple races',
                                '97'='Refused','98'='Not ascertained','99'='unknown')




data_new2 <- data_new %>% select(CVDDIAG_A, COVIDTEST_A, DLYCARE_A, DNGCARE_A, VIRAPP12M_A,HOMECAREDG_A, FAMCARE12M_A, FAMCAREDNG_A) 

data_new <- data_new[!apply(data_new2,1,function(x) any(x %in% c('Refused','Not ascertained','unknown'))),]
```


```{r}
```