---
title: "Weighted Logistic Regression Sample"
author: "Yuelin He"
date: "7/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(srvyr)
library(survey)
```

### Preprocessing
```{r preprocessing, message=FALSE}
nhis <- read_csv("./nhis_clean.csv")

# factoring (** set the reference levels)
nhis$RACE <- as.factor(nhis$RACE)
nhis$RACE <- relevel(nhis$RACE, ref = "NHW")
nhis$EDUC <- factor(nhis$EDUC, levels = c("Less Than High School", "High School Graduate/GED/Some College", "College Degree"))
nhis$MARITAL <- factor(nhis$MARITAL, levels = c("Never Married", "Divorced/Separated", "Widowed", "Married"))
nhis$FAMINC <- factor(nhis$FAMINC, levels = c("<10K", "<25K", "<45K", "<75K", "+75K"))
nhis$AGE <- factor(nhis$AGE, levels = c("18 ~ 25", "26 ~ 44", "45 ~ 64", "+65"))
nhis$PHSTAT <- factor(nhis$PHSTAT, levels = c("Poor", "Fair", "Good", "Very good", "Excellent"))
nhis$COVERAGE <- as.factor(nhis$COVERAGE)
nhis$COVERAGE <- relevel(nhis$COVERAGE, ref = "Not Covered")
```

### Survey Object
```{r}
nhisDesign <- nhis %>%
  as_survey_design( # might need to change based on our variable names and design
    ids = NPSU,
    strata = NSTRATUM,
    weights = WTFA_SA,
    nest = TRUE
  )

nhisDesign <- subset(nhisDesign, !(MD == "None" | RACE == "Others")) # remove people with no mental distress and other races // in our case, we can remove those with NA in OUTCOME
```

### Multiple Logistic Regression
```{r}
logit.complexfull <- svyglm(
  AHCSYR1 ~ RACE + SEX + AGE + EDUC + FAMINC + MARITAL + PLBORN + LIMIT + MD + PHSTAT + COVERAGE + GMC + YEAR, # change the equation here
  family = quasibinomial(), 
  design = nhisDesign
)

summary(logit.complexfull)
```

### Create a nice custom forest Plot
```{r}
or <- exp(coef(logit.complexfull)) # extract and exponentiate coefs
se <- sqrt(diag(vcov(logit.complexfull))) # extract Var and covert to SE
lower <- exp(coef(logit.complexfull) - qnorm(0.975) * se) # 95% C.I. lower bound
upper <- exp(coef(logit.complexfull) + qnorm(0.975) * se) # 95% C.I. higher bound
tmp <- data.frame(cbind(or, lower, upper)) # create data frame
tmp
```

```{r}
clean.names <- c( # Rename the rows so that there is a ":" and " " separating the variable name and strata
  "(Intercept)",
  "RACE: Asian Indian",
  "RACE: Chinese",
  "RACE: Filipino",
  "SEX: Male",
  "AGE: 26~44",
  "AGE: 45~64",
  "AGE: +65",
  "EDUC: HS Graduate/GED/Some College",
  "EDUC: College Degree",
  "FAMINC: <25K",
  "FAMINC: <45K",
  "FAMINC: <75K",
  "FAMINC: +75K",
  "MARITAL: Divorced/Separated",
  "MARITAL: Widowed",	
  "MARITAL: Married",
  "PLBORN: Yes",
  "LIMIT: Yes",
  "MD: Moderate",
  "MD: Severe",
  "PHSTAT: Fair",
  "PHSTAT: Good",
  "PHSTAT: Very good",
  "PHSTAT: Excellent",
  "COVERAGE: Covered",
  "GMC: Yes",
  "YEAR"
) # also need to change

row.names(tmp) <- clean.names
odds <- tmp[-1, ]

# Creating reference points
ref.age <- data.frame(row.names = "(Reference) AGE: 18~25", or = 1, lower = 1, upper = 1)
ref.sex <- data.frame(row.names = "(Reference) SEX: Female", or = 1, lower = 1, upper = 1)
ref.race <- data.frame(row.names = "(Reference) RACE: NHW", or = 1, lower = 1, upper = 1)
ref.educ <- data.frame(row.names = "(Reference) EDUC: Less than HS", or = 1, lower = 1, upper = 1)
ref.faminc <- data.frame(row.names = "(Reference) FAMINC: <10K", or = 1, lower = 1, upper = 1)
ref.marital <- data.frame(row.names = "(Reference) MARITAL: Never Married", or = 1, lower = 1, upper = 1)
ref.md <- data.frame(row.names = "(Reference) MD: Mild", or = 1, lower = 1, upper = 1)
ref.limit <- data.frame(row.names = "(Reference) LIMIT: No", or = 1, lower = 1, upper = 1)
ref.coverage <- data.frame(row.names = "(Reference) COVERAGE: Not Covered", or = 1, lower = 1, upper = 1)
ref.gmc <- data.frame(row.names = "(Reference) GMC: No", or = 1, lower = 1, upper = 1)
ref.plborn <- data.frame(row.names = "(Reference) PLBORN: No", or = 1, lower = 1, upper = 1)
ref.phstat <- data.frame(row.names = "(Reference) PHSTAT: Poor", or = 1, lower = 1, upper = 1)

odds
```

```{r}
odds <- rbind(
  ref.race, odds[1:3,],
  ref.sex, odds[4,],
  ref.age, odds[5:7,],
  ref.educ, odds[8:9,],
  ref.faminc, odds[10:13,],
  ref.marital, odds[14:16,],
  ref.plborn, odds[17,],
  ref.limit, odds[18,],
  ref.md, odds[19:20,],
  ref.phstat, odds[21:24,],
  ref.coverage, odds[25,],
  ref.gmc, odds[26:27,]
)
```

```{r}
odds$vars <- row.names(odds) # create a new column called vars
odds <- odds %>% # create a new column called category and sort the variables into the category you want. This is used later to add the colors.
  mutate(
    category = case_when(
      str_match(vars, "[A-Z]+:") == "AGE:" ~ "SocioDemographic",
      str_match(vars, "[A-Z]+:") == "SEX:" ~ "SocioDemographic",
      str_match(vars, "[A-Z]+:") == "EDUC:" ~ "SocioDemographic",
      str_match(vars, "[A-Z]+:") == "FAMINC:" ~ "SocioDemographic",
      str_match(vars, "[A-Z]+:") == "MARITAL:" ~ "SocioDemographic",
      str_match(vars, "[A-Z]+:") == "PLBORN:" ~ "SocioDemographic",
      str_match(vars, "[A-Z]+:") == "LIMIT:" | str_match(vars, "[A-Z]+:") == "PHSTAT:" ~ "Life Style",
      str_match(vars, "[A-Z]+:") == "COVERAGE:" | str_match(vars, "[A-Z]+:") == "GMC:" ~ "Health Care",
      str_match(vars, "[A-Z]+:") == "MD:" ~ "Health Status",
      str_match(vars, "[A-Za-z]+") == "YEAR" ~ "Year",
      str_match(vars, "[A-Z]+: NHW") == "RACE: NHW" ~ "RACE: NHW",
      str_match(vars, "[A-Z]+: Asian Indian") == "RACE: Asian Indian" ~ "RACE: Asian Indian",
      str_match(vars, "[A-Z]+: Chinese") == "RACE: Chinese" ~ "RACE: Chinese",
      str_match(vars, "[A-Z]+: Filipino") == "RACE: Filipino" ~ "RACE: Filipino"
    )
  )
```

```{r}
# factoring the vars and categories column so that they stay in order went we plot them
odds$vars <- factor(odds$vars, levels=rev(odds$vars))

odds$category <- factor(odds$category, levels = c("RACE: NHW", "RACE: Chinese", "RACE: Filipino", "RACE: Asian Indian", "SocioDemographic", "Life Style", "Mental Distress", "Health Status", "Health Care", "Year"))

color.schema <- c("#0D0D0D", "#8C0303", "#3D7345", "#BB7A32", "#DDB247", "#4B7210", "#519188", "#14312A", "#653040") # make sure the ordering of the color is the same as the ordering of the variable categories above.
```

```{r, fig.height=6, fig.width=4.6, dpi=300}
ggplot(odds, aes(y = or, x = vars, color=category)) + 
  geom_hline(yintercept = 1, linetype = 2) + 
  geom_point(size=6) + 
  geom_errorbar(aes(ymin = lower, ymax = upper), width = .2) + 
  scale_y_log10() + 
  coord_flip() + 
  annotate("text", y = rev(odds$or), x = 1:nrow(odds), label = round(rev(odds$or), 2), size=2, color="white") + 
  scale_colour_manual(values = color.schema) + 
  labs(
    title = "Mental Health Service Utilization",
    subtitle = "Multiple Logistic Regression",
    x = element_blank(),
    y = "Odds Ratio",
    caption = "National Health Interview Survey (2006 ~ 2018)"
  ) +
  theme_bw() +
  theme(axis.text.y = element_text(size = 11))
```
