---
title: "weighted_logistic regression"
author: "Yuelin He"
date: "2021/12/13"
output: pdf_document
---

```{r}
library(tidyverse)
library(srvyr)
library(survey)
library(svyVGAM)
full <- read.csv("adult20.csv")
```


# For each of the imputed value

# adding the survey-related variables back to the dataset to be used

```{r}
imputed1 <- read.csv("imputed dataset/imp_data1.csv")
imputed1$HHX <- full$HHX
imputed1$WTFA_A <- full$WTFA_A
imputed1$PSTRAT <- full$PSTRAT
imputed1$PPSU <- full$PPSU
```

```{r}
imputed1_new <- imputed1 %>% select(
  ##survey design
  HHX, WTFA_A, URBRRL, REGION, PSTRAT, PPSU,
  ## outcome
  MHRX_A, MHTHRPY_A, # mental health
  DEPEV_A, DEPFREQ_A, DEPMED_A, # depression
  ANXEV_A, ANXFREQ_A, ANXMED_A, # anxiety
  ##predictors, contain the imputed values
  CVDDIAG_A, COVIDTEST_A, 
  DLYCARE_A, DNGCARE_A, VIRAPP12M_A, 
  HOMECAREDG_A, FAMCAREDNG_A, 
  ##confounders ## no NAs
  AGEP_A, SEX_A, EDUC_A, 
  HISPALLP_A# r/e
  )

# recode yes/no data
binary_var <- c("MHRX_A", "MHTHRPY_A", "DEPEV_A", "DEPMED_A", "ANXEV_A", "ANXMED_A", "CVDDIAG_A", "COVIDTEST_A", "DLYCARE_A", "DNGCARE_A", "VIRAPP12M_A", "HOMECAREDG_A", "FAMCAREDNG_A")
for (i in binary_var){
  imputed1_new[,i] <- ifelse(imputed1_new[,i]>=7,NA,imputed1_new[,i])
  imputed1_new[,i] <- ifelse(is.na(imputed1_new[,i]),'Unknown',imputed1_new[,i])
  imputed1_new[,i] <- dplyr::recode(as.character(imputed1_new[,i]),
                                '1'='Yes','2'='No')
  imputed1_new[,i] <- factor(imputed1_new[,i],levels=c('No','Yes','Unknown'))
}

# recode frequency data
for (i in c('DEPFREQ_A','ANXFREQ_A')){
  imputed1_new[,i] <- ifelse(imputed1_new[,i]>=7,NA,imputed1_new[,i])
  imputed1_new[,i] <- dplyr::recode(as.character(imputed1_new[,i]),
                                '1'='Daily','2'='Weekly','3'='Monthly',
                                '4'='A few times a year','5'='Never')
  imputed1_new[,i] <- factor(imputed1_new[,i],levels=c('Never','A few times a year','Monthly','Weekly','Daily'))
}

# recode others
imputed1_new[,'SEX_A'] <- dplyr::recode(as.character(imputed1_new[,'SEX_A']),
                                '1'='Male','2'='Female','7'='Refused or Unknown',
                                '8'='Refused or Unknown','9'='Refused or Unknown')
imputed1_new$EDUC_A <- ifelse(imputed1_new$EDUC_A<=11&imputed1_new$EDUC_A>=5,5,imputed1_new$EDUC_A)
imputed1_new$EDUC_A <- ifelse(imputed1_new$EDUC_A<=4,0,imputed1_new$EDUC_A)
imputed1_new$EDUC_A <- ifelse(imputed1_new$EDUC_A%in% c(0,5),imputed1_new$EDUC_A,"Unknown")
imputed1_new$EDUC_A <- dplyr::recode(as.character(imputed1_new$EDUC_A),
                                '0'='High School or Below','5'='College or Above')
imputed1_new$EDUC_A <- relevel(as.factor(imputed1_new$EDUC_A),ref='High School or Below')
imputed1_new$HISPALLP_A <- dplyr::recode(as.character(imputed1_new$HISPALLP_A),
                                '1'='Hispanic','2'='NH White',
                                '3'='Black/African American','4'='Asian',
                                '5'='AIAN and any other group','6'='AIAN and any other group',
                                '7'='Other single and multiple races',
                                '97'='Refused','98'='Not ascertained','99'='unknown')
imputed1_new$HISPALLP_A <- relevel(as.factor(imputed1_new$HISPALLP_A),ref="NH White")

## categorize age?? ('97'='Refused','98'='Not ascertained','99'='unknown')

imputed1_new$AGEP_A <- case_when(
  imputed1_new$AGEP_A<=44 & imputed1_new$AGEP_A>=18 ~ "18-44",
  imputed1_new$AGEP_A<=64 & imputed1_new$AGEP_A>=45 ~ "45-64",
  imputed1_new$AGEP_A<=85 & imputed1_new$AGEP_A>=65 ~ "65+",
  TRUE ~ "Unknown"
)
# table(imputed1_new$AGEP_A)
```

# Fit model for binary outcomes

```{r}
# Each time fitting a model, remove only its own unknown outcomes
or.df <- list()
for (i in binary_var[1:6]){
  imputed1_mhrx <- imputed1_new[imputed1_new[,i]!="Unknown",]
  design1mhrx <- imputed1_mhrx %>%
    as_survey_design( # might need to change based on our variable names and design
      ids = HHX,
      strata = PSTRAT,
      weights = WTFA_A,
      nest = TRUE
    )
  imputed1_mhrx[,i] <- as.integer(ifelse(imputed1_mhrx[,i]=='Yes',1,0))
  
  logit.formula <- as.formula(paste(i,'~CVDDIAG_A + COVIDTEST_A + DLYCARE_A + DNGCARE_A + VIRAPP12M_A + HOMECAREDG_A + FAMCAREDNG_A + AGEP_A + SEX_A + EDUC_A + HISPALLP_A',collapse=''))
  MHRX_A_imputed1_logit <- svyglm(
    logit.formula,
    family = quasibinomial(), 
    design = design1mhrx
  )
  print(i)
  print(summary(MHRX_A_imputed1_logit))
  or <- exp(coef(MHRX_A_imputed1_logit)) # extract and exponentiate coefs
  se <- sqrt(diag(vcov(MHRX_A_imputed1_logit))) # extract Var and covert to SE
  lower <- exp(coef(MHRX_A_imputed1_logit) - qnorm(0.975) * se) # 95% C.I. lower bound
  upper <- exp(coef(MHRX_A_imputed1_logit) + qnorm(0.975) * se) # 95% C.I. higher bound
  p.val <- summary(MHRX_A_imputed1_logit)$coefficients[,4]
  or.df[[length(or.df)+1]] <- data.frame(cbind(or, lower, upper,p.val)) # create data frame
}
```

# Forest plots

```{r}
outcome.vars <- c("Took medicine for mental health","Received counseling for mental health","Ever had depression",
                      "Take medication for depression","Ever had anxiety","Take medication for anxiety")

for (i in 1:6){
  temp.df <- or.df[[i]][-c(1,11,13,15,20),] # drop the unknown/refused/others categories
  temp.df$vars <- c("Ever had COVID","Ever been tested for COVID","Delayed medical care","Unreceived medical care","Virtual medical appointment","Unreceived home care","Unreceived family care","Age=45-64","Age=65+","Sex=Male","Education=College or Above","Race=AIAN","Race=Asian","Race=Black","Race=Hispanic")
  temp.df$vars <- factor(temp.df$vars, levels=rev(temp.df$vars))
  
  temp.df$variable.types <- factor(c("COVID test","COVID test",rep("Changed medical care due to COVID",3),rep("Changed home/family care due to COVID",2),rep("Demographic",8)),
                                levels=c("COVID test","Changed medical care due to COVID",
    "Changed home/family care due to COVID","Demographic"))
  
  print(ggplot(temp.df, aes(y = or, x = vars, color=variable.types)) + 
    geom_hline(yintercept = 1, linetype = 2) + 
    geom_point(size=6) + 
    geom_errorbar(aes(ymin = lower, ymax = upper), width = .2) + 
    scale_y_log10() + 
    coord_flip() + 
    annotate("text", y = rev(temp.df$or), x = 1:nrow(temp.df), label = round(rev(temp.df$or), 2), size=2, color="white") + 
    # scale_colour_manual(values = color.schema) + 
    labs(
      title = outcome.vars[i],
      x = element_blank(),
      y = "Odds Ratio",
      # caption = "National Health Interview Survey (2006 ~ 2018)"
    ) +
    theme_bw() +
    theme(axis.text.y = element_text(size = 11)))
}

```






# Fit model for multi-categories outcomes -> take long to run, hard to interpret

```{r}
# Each time fitting a model, remove only its own unknown outcomes

for (i in c('DEPFREQ_A','ANXFREQ_A')){
  imputed1_mhrx <- imputed1_new[!is.na(imputed1_new[,i]),]
  design1mhrx <- imputed1_mhrx %>%
    as_survey_design( # might need to change based on our variable names and design
      ids = HHX,
      strata = PSTRAT,
      weights = WTFA_A,
      nest = TRUE
    )
  logit.formula <- as.formula(paste(i,'~CVDDIAG_A + COVIDTEST_A + DLYCARE_A + DNGCARE_A + VIRAPP12M_A + HOMECAREDG_A + FAMCAREDNG_A + AGEP_A + SEX_A + EDUC_A + HISPALLP_A',collapse=''))
  MHRX_A_imputed1_logit <- svy_vglm(#svyVGAM package
    logit.formula,
    family=multinomial, 
    design = design1mhrx
  )
  print(i)
  print(summary(MHRX_A_imputed1_logit))
  }
```

# Fit model for multiple outcomes - second approach
# Memory exhausted on my laptop

```{r, eval=FALSE} 
# Each time fitting a model, remove only its own unknown outcomes

for (i in c('DEPFREQ_A','ANXFREQ_A')){
  imputed1_mhrx <- imputed1_new[!is.na(imputed1_new[,i]),]
  design1mhrx <- imputed1_mhrx %>%
    as_survey_design( # might need to change based on our variable names and design
      ids = HHX,
      strata = PSTRAT,
      weights = WTFA_A,
      nest = TRUE
    )
  logit.formula <- as.formula(paste(i,'~CVDDIAG_A + COVIDTEST_A + DLYCARE_A + DNGCARE_A + VIRAPP12M_A + HOMECAREDG_A + FAMCAREDNG_A + AGEP_A + SEX_A + EDUC_A + HISPALLP_A',collapse=''))
  MHRX_A_imputed1_logit <- svyolr(#survey package
    logit.formula,
    design = as.svrepdesign(design1mhrx),
    method='logistic'
  )
  print(i)
  print(summary(MHRX_A_imputed1_logit))
  }
```






