---
title: "MissForest Package"
author: "Vicky"
date: "11/14/2021"
output: pdf_document
---
# https://ftp.cdc.gov/pub/Health_Statistics/NCHS/Dataset_Documentation/NHIS/2020/adult-codebook.pdf
```{r}
library(dplyr)
library(tidyr)
library(srvyr)
library(ggplot2)
library(corrplot)
library(tidyverse)
adult20 = read.csv("C:\\Users\\hevic\\OneDrive\\Desktop\\625project\\covid_income_mental_employment.csv")
```
```{r}
miss_impute <- adult20[,!apply(adult20,2,function(x){sum(is.na(x))>nrow(adult20)/2})]
removed_var <- c("HHX","RECTYPE","SRVY_YR","PPSU","WTFA_A","PSTRAT","PPSU","HHSTAT_A","ASTATNEW")
miss_impute <- miss_impute[,!colnames(miss_impute) %in% removed_var]
```
```{r}
#data=adult20 %>% select(MHRX_A,MHTHRPY_A,MHTHDLY_A,MHTHND_A,DEPFREQ_A,DEPMED_A,ANXFREQ_A, ANXMED_A,CVDDIAG_A,COVIDTEST_A,DLYCARE_A,DNGCARE_A,VIRAPP12M_A, HOMECAREDG_A,FAMCAREDNG_A, AGEP_A, SEX_A, EDUC_A, HISP_A, HISPALLP_A, HISDETP_A, RACEALLP_A, RECTYPE, HHX, WTFA_A, URBRRL, REGION, PSTRAT, PPSU)
#data = data %>% drop_na(CVDDIAG_A,COVIDTEST_A,DLYCARE_A,DNGCARE_A,VIRAPP12M_A,HOMECAREDG_A,FAMCAREDNG_A)
```
```{r}
# require observations(row) to be pairwise independent
library(missForest)
impute_var <- c("CVDDIAG_A", "COVIDTEST_A", "DLYCARE_A", "DNGCARE_A", 
                "VIRAPP12M_A", "HOMECAREDG_A",  "FAMCAREDNG_A")
for (i in impute_var){
  miss_impute[,i] <- ifelse(miss_impute[,i]>=7,NA,miss_impute[,i])
}
miss_impute[,impute_var] <- lapply(miss_impute[,impute_var] , factor)
```
```{r}
temp <- miss_impute[,!colnames(miss_impute) %in% impute_var]
impute <- miss_impute[,colnames(miss_impute) %in% impute_var]
temp <- temp[,!apply(temp,2,function(x){sum(is.na(x))>0})]
final <- cbind(temp,impute)
```
```{r}
result <- missForest(final)#,verbose = TRUE)
result$ximp
```
